### ISSUE TITLE
How to run it on Ubuntu and windows 64bit

### ISSUE THREAD

**Issue by b-thebest** [MennovDijk/bilge_bot#1]
Could you please write about how to use it during game windows opened in windows 64bit or Ubuntu operating system? 
I want to make bot for poker, please suggest me way to do it. Would be some part of this code cam help me to achieve my goal?

**Comment by matheusbonjour** [comment]
@b-thebest 
i used on windows 64bit, through pycharm. you just need to define your name and the ocean you play in, in the script "pywin32_grabwindow.py".

the variable "hwnd" is a string that must have the name of the window where the puzzle pirates is located: "Puzzle Pirates - Friend on the Emerald Ocean"

after running "pywin32_grabwindow.py", you must open "main.py" and run it. this done, the puzzle will be solved automatically.

**Comment by MennovDijk** [comment]
@jaboncean  Thanks for explaining it, that's how you should do it. Honestly, the goal of this project was never to get people to massively start botting this puzzle (there are way better open-source bots out there to do that for you). I was really just interested in seeing if I could do it.

@b-thebest The code right now is set up in such a way that it really only grabs the bilging window. If you want to go and rewrite the code to do poker, you'd have to set up the dimensions of the poker window, change the images that it can detect, etc etc.
